/**
 * N18: Export ABIs from compiled Hardhat artifacts to contracts/abis/.
 *
 * Reads every contract artifact from artifacts/sol/, extracts the ABI
 * and bytecode, writes one JSON file per contract, and generates a
 * TypeScript index re-exporting all ABIs.
 *
 * Usage:  npx hardhat compile && node scripts/export-abis.js
 *   or:   npm run export-abis
 */
const fs = require('fs');
const path = require('path');

const ARTIFACTS_DIR = path.join(__dirname, '..', 'artifacts', 'sol');
const OUT_DIR = path.join(__dirname, '..', 'abis');

if (!fs.existsSync(ARTIFACTS_DIR)) {
  console.error('Artifacts directory not found — run `npx hardhat compile` first.');
  process.exit(1);
}

if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

const solDirs = fs.readdirSync(ARTIFACTS_DIR).filter((d) => {
  return fs.statSync(path.join(ARTIFACTS_DIR, d)).isDirectory();
});

const exported = [];

for (const solDir of solDirs) {
  const dirPath = path.join(ARTIFACTS_DIR, solDir);
  const jsonFiles = fs.readdirSync(dirPath).filter(
    (f) => f.endsWith('.json') && !f.endsWith('.dbg.json'),
  );

  for (const jsonFile of jsonFiles) {
    const artifactPath = path.join(dirPath, jsonFile);
    const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));

    if (!artifact.abi || artifact.abi.length === 0) continue;

    const name = path.basename(jsonFile, '.json');
    const outPath = path.join(OUT_DIR, `${name}.json`);

    fs.writeFileSync(
      outPath,
      JSON.stringify({ contractName: name, abi: artifact.abi, bytecode: artifact.bytecode }, null, 2),
    );

    exported.push(name);
    console.log(`  ✓ ${name}`);
  }
}

if (exported.length === 0) {
  console.warn('No contract artifacts found. Did you compile first?');
  process.exit(1);
}

const indexLines = [
  '// Auto-generated by scripts/export-abis.js — do not edit manually',
  '',
];

for (const name of exported.sort()) {
  indexLines.push(`import ${name}ABI from './${name}.json';`);
}

indexLines.push('');
indexLines.push(`export { ${exported.sort().map((n) => `${n}ABI`).join(', ')} };`);
indexLines.push('');

fs.writeFileSync(path.join(OUT_DIR, 'index.ts'), indexLines.join('\n'));

console.log(`\nExported ${exported.length} contract ABIs to ${OUT_DIR}`);
console.log('Generated abis/index.ts');
