# Fail2ban filter for jet.coindaily.online
# /etc/fail2ban/filter.d/coindaily-admin.conf

[Definition]
failregex = ^<HOST> .* ".*" 444 0
            ^<HOST> .* "(GET|POST|PUT|DELETE) /admin.*" (401|403|444)
            ^<HOST> .* ".*" 400
ignoreregex =
