/**
 * Seed data for 40-country regulatory database.
 * 
 * Coverage:
 * - Africa (14): Nigeria, Kenya, South Africa, Ghana, Tanzania, Uganda, Rwanda, Mauritius, Seychelles, Egypt, Ethiopia, Namibia, Botswana, Zambia
 * - Caribbean (8): Jamaica, Trinidad & Tobago, Barbados, Bahamas, Cayman Islands, BVI, Haiti, Dominican Republic
 * - Latin America (11): Brazil, Argentina, Colombia, Mexico, Venezuela, Chile, Peru, Ecuador, Panama, Uruguay, El Salvador
 * - Additional (7): UAE, Singapore, UK, India, Indonesia, Philippines, Thailand
 */

export const regulatoryCountrySeedData = [
  // ═══════════════ AFRICA (14) ═══════════════
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    region: 'WEST_AFRICA',
    legalStatus: 'REGULATED',
    riskScore: 62,
    licensingRequired: true,
    licensingFramework: 'Nigeria Investments & Securities Act 2025 — digital assets formally recognized. SEC Nigeria oversees VASPs.',
    taxFramework: 'Capital gains tax on crypto profits. Reporting thresholds under development.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'GREY_LIST',
    cbdcStatus: 'eNaira launched (2021) — low adoption',
    centralBankStance: 'Cautious — lifted 2021 banking ban, now regulated through SEC.',
    enforcementHistory: 'Binance operations restricted 2024. P2P regulation tightening.',
    upcomingLegislation: 'Digital Assets Bill amendments expected 2026',
    stablecoinRules: 'Under SEC framework — issuer licensing in development',
    keyRegulator: 'Securities and Exchange Commission (SEC Nigeria)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    region: 'EAST_AFRICA',
    legalStatus: 'REGULATED',
    riskScore: 68,
    licensingRequired: true,
    licensingFramework: 'Kenya VASP Act 2025 — dual-regulator model: CBK (payments) + CMA (securities).',
    taxFramework: 'Digital asset tax at 3% on transfers (Finance Act 2023). Capital gains being debated.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase — CBK digital shilling study ongoing',
    centralBankStance: 'Progressive — dual-regulator approach seen as balanced.',
    enforcementHistory: 'WorldCoin biometric data concerns. Mobile money crypto integration scrutiny.',
    upcomingLegislation: 'CMA digital securities sandbox expansion',
    stablecoinRules: 'Under CBK payments regulation framework',
    keyRegulator: 'Capital Markets Authority (CMA) + Central Bank of Kenya (CBK)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    region: 'SOUTHERN_AFRICA',
    legalStatus: 'REGULATED',
    riskScore: 78,
    licensingRequired: true,
    licensingFramework: 'CASP (Crypto Asset Service Provider) licensing via FSCA. FAIS Act amendment covers crypto.',
    taxFramework: 'Capital gains tax applicable. SARS treats crypto as intangible assets.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'GREY_LIST',
    cbdcStatus: 'Project Khokha 2 — wholesale CBDC pilot completed',
    centralBankStance: 'Constructive — SARB supportive of innovation with guardrails.',
    enforcementHistory: 'Mirror Trading International ($1.7B fraud case). Africrypt collapse.',
    upcomingLegislation: 'CASP licensing deadline extensions. Stablecoin-specific regulation.',
    stablecoinRules: 'Covered under CASP licensing framework',
    keyRegulator: 'Financial Sector Conduct Authority (FSCA)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    region: 'WEST_AFRICA',
    legalStatus: 'DEVELOPING',
    riskScore: 55,
    licensingRequired: false,
    licensingFramework: 'Bank of Ghana working on comprehensive framework. Digital Financial Services Policy in progress.',
    taxFramework: 'No specific crypto tax legislation yet. General income tax may apply.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'e-Cedi pilot completed — rollout decision pending',
    centralBankStance: 'Cautious — studying regulatory approaches from peers.',
    enforcementHistory: 'BoG warnings against unlicensed platforms. No major enforcement.',
    upcomingLegislation: 'Comprehensive crypto regulation expected by end 2026',
    stablecoinRules: 'Not yet regulated',
    keyRegulator: 'Bank of Ghana (BoG)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    region: 'EAST_AFRICA',
    legalStatus: 'DEVELOPING',
    riskScore: 45,
    licensingRequired: false,
    licensingFramework: 'Bank of Tanzania exploring regulatory framework. Currently no specific crypto legislation.',
    taxFramework: 'No specific crypto tax framework.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Early research stage',
    centralBankStance: 'Cautious — previously warned against crypto, now exploring regulation.',
    enforcementHistory: 'Minimal enforcement actions.',
    upcomingLegislation: 'Digital asset regulation study underway',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Bank of Tanzania (BoT)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    region: 'EAST_AFRICA',
    legalStatus: 'DEVELOPING',
    riskScore: 42,
    licensingRequired: false,
    licensingFramework: 'New licensing framework being developed. OneCoin enforcement case drove regulatory interest.',
    taxFramework: 'No specific crypto tax legislation.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'No CBDC plans announced',
    centralBankStance: 'Cautious but open — working with industry stakeholders.',
    enforcementHistory: 'OneCoin fraud case. BOU has issued caution notices.',
    upcomingLegislation: 'Virtual asset regulation bill in draft stage',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Bank of Uganda (BOU)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    region: 'EAST_AFRICA',
    legalStatus: 'DEVELOPING',
    riskScore: 60,
    licensingRequired: false,
    licensingFramework: 'BNR (National Bank of Rwanda) developing sandbox framework for digital assets.',
    taxFramework: 'No specific crypto tax framework yet.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase',
    centralBankStance: 'Progressive — aligns with Rwanda\'s innovation hub strategy.',
    enforcementHistory: 'Minimal — small market.',
    upcomingLegislation: 'Digital economy bill includes crypto provisions',
    stablecoinRules: 'Not yet regulated',
    keyRegulator: 'National Bank of Rwanda (BNR)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'MU',
    countryName: 'Mauritius',
    region: 'EAST_AFRICA',
    legalStatus: 'REGULATED',
    riskScore: 82,
    licensingRequired: true,
    licensingFramework: 'Virtual Asset and Initial Token Offering Services Act 2021. FSC Mauritius issues VASP licenses.',
    taxFramework: 'No capital gains tax. Corporate tax on crypto business profits.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase',
    centralBankStance: 'Progressive — positioning as African crypto hub.',
    enforcementHistory: 'Strong compliance-focused enforcement.',
    upcomingLegislation: 'DeFi regulation framework expected 2026',
    stablecoinRules: 'Covered under VASP Act',
    keyRegulator: 'Financial Services Commission (FSC Mauritius)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'SC',
    countryName: 'Seychelles',
    region: 'EAST_AFRICA',
    legalStatus: 'REGULATED',
    riskScore: 75,
    licensingRequired: true,
    licensingFramework: 'FSA Seychelles issues Digital Asset Business licenses under Securities Act.',
    taxFramework: 'No income tax on crypto. Business registration tax applies.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'No plans',
    centralBankStance: 'Supportive — multiple exchanges registered.',
    enforcementHistory: 'FTX was registered in Seychelles. Tightening oversight post-FTX.',
    upcomingLegislation: 'Enhanced VASP oversight regulations',
    stablecoinRules: 'Under Digital Asset Business licensing',
    keyRegulator: 'Financial Services Authority (FSA Seychelles)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    region: 'NORTH_AFRICA',
    legalStatus: 'RESTRICTED',
    riskScore: 30,
    licensingRequired: false,
    licensingFramework: 'No licensing framework. CBE prohibits banks from crypto transactions.',
    taxFramework: 'No specific crypto tax legislation. General tax laws may apply.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'CBE studying CBDC options',
    centralBankStance: 'Restrictive — banking ban on crypto transactions.',
    enforcementHistory: 'Banking restrictions enforced. No major criminal prosecution.',
    upcomingLegislation: 'Potential digital currency regulation under IMF pressure',
    stablecoinRules: 'Not permitted',
    keyRegulator: 'Central Bank of Egypt (CBE)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'ET',
    countryName: 'Ethiopia',
    region: 'EAST_AFRICA',
    legalStatus: 'RESTRICTED',
    riskScore: 25,
    licensingRequired: false,
    licensingFramework: 'No framework. NBE has not issued crypto-specific guidelines.',
    taxFramework: 'No crypto-specific tax framework.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'GREY_LIST',
    cbdcStatus: 'No CBDC plans',
    centralBankStance: 'Restrictive — crypto trading discouraged.',
    enforcementHistory: 'Telebirr mobile money dominates. Crypto suppressed.',
    upcomingLegislation: 'No known legislative activity on crypto',
    stablecoinRules: 'Not permitted',
    keyRegulator: 'National Bank of Ethiopia (NBE)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'NA',
    countryName: 'Namibia',
    region: 'SOUTHERN_AFRICA',
    legalStatus: 'DEVELOPING',
    riskScore: 50,
    licensingRequired: false,
    licensingFramework: 'Bank of Namibia studying regulation. Virtual Asset Bill in draft.',
    taxFramework: 'No specific crypto tax framework.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase',
    centralBankStance: 'Cautious — monitoring South Africa\'s CASP framework.',
    enforcementHistory: 'Minimal.',
    upcomingLegislation: 'Virtual Asset Bill expected 2026',
    stablecoinRules: 'Not yet regulated',
    keyRegulator: 'Bank of Namibia (BoN)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'BW',
    countryName: 'Botswana',
    region: 'SOUTHERN_AFRICA',
    legalStatus: 'DEVELOPING',
    riskScore: 48,
    licensingRequired: false,
    licensingFramework: 'No specific crypto legislation. Bank of Botswana monitoring developments.',
    taxFramework: 'General tax principles may apply.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'No CBDC plans announced',
    centralBankStance: 'Cautious but not hostile.',
    enforcementHistory: 'No major enforcement.',
    upcomingLegislation: 'Studying regional regulatory frameworks',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Bank of Botswana',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'ZM',
    countryName: 'Zambia',
    region: 'SOUTHERN_AFRICA',
    legalStatus: 'DEVELOPING',
    riskScore: 45,
    licensingRequired: false,
    licensingFramework: 'Bank of Zambia developing technology-neutral regulations.',
    taxFramework: 'No specific crypto tax framework.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Early research',
    centralBankStance: 'Open to innovation — SEC working on framework.',
    enforcementHistory: 'Minimal enforcement.',
    upcomingLegislation: 'Digital Financial Services Bill in pipeline',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Bank of Zambia (BoZ) + Securities and Exchange Commission',
    lastUpdated: new Date(),
  },

  // ═══════════════ CARIBBEAN (8) ═══════════════
  {
    countryCode: 'JM',
    countryName: 'Jamaica',
    region: 'CARIBBEAN',
    legalStatus: 'DEVELOPING',
    riskScore: 55,
    licensingRequired: false,
    licensingFramework: 'Bank of Jamaica studying crypto regulation. Securities Commission exploring token regulation.',
    taxFramework: 'No specific crypto tax framework. General income tax applies.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'JAM-DEX (CBDC) launched 2022 — scaling efforts ongoing',
    centralBankStance: 'Cautious but progressive — JAM-DEX shows openness.',
    enforcementHistory: 'Minimal. FSC warnings about unregistered schemes.',
    upcomingLegislation: 'Virtual asset regulation framework under development',
    stablecoinRules: 'Not yet regulated',
    keyRegulator: 'Bank of Jamaica (BoJ) + Financial Services Commission',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'TT',
    countryName: 'Trinidad & Tobago',
    region: 'CARIBBEAN',
    legalStatus: 'DEVELOPING',
    riskScore: 50,
    licensingRequired: false,
    licensingFramework: 'Central Bank reviewing crypto regulation framework. TTSEC monitoring token offerings.',
    taxFramework: 'No specific crypto tax legislation.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase',
    centralBankStance: 'Cautious — multiple advisories issued.',
    enforcementHistory: 'CBTT advisories about crypto risks.',
    upcomingLegislation: 'Digital asset framework discussions ongoing',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Central Bank of Trinidad & Tobago',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'BB',
    countryName: 'Barbados',
    region: 'CARIBBEAN',
    legalStatus: 'DEVELOPING',
    riskScore: 60,
    licensingRequired: false,
    licensingFramework: 'Central Bank of Barbados monitoring. FSC exploring fintech sandbox.',
    taxFramework: 'No specific crypto tax legislation. Capital gains not taxed.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'DCash (ECCB) available — Eastern Caribbean digital currency',
    centralBankStance: 'Open to innovation — active in ECCB digital currency.',
    enforcementHistory: 'Minimal.',
    upcomingLegislation: 'Fintech sandbox expansion',
    stablecoinRules: 'Not specifically regulated',
    keyRegulator: 'Central Bank of Barbados + Financial Services Commission',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'BS',
    countryName: 'Bahamas',
    region: 'CARIBBEAN',
    legalStatus: 'REGULATED',
    riskScore: 72,
    licensingRequired: true,
    licensingFramework: 'DARE Act 2020 (Digital Assets and Registered Exchanges). SCB licenses digital asset businesses.',
    taxFramework: 'No income tax, capital gains tax, or crypto-specific tax.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Sand Dollar — world\'s first CBDC (launched 2020)',
    centralBankStance: 'Very progressive — leading CBDC globally.',
    enforcementHistory: 'FTX bankruptcy (headquartered in Bahamas) triggered major review.',
    upcomingLegislation: 'Post-FTX DARE Act amendments for enhanced oversight',
    stablecoinRules: 'Covered under DARE Act',
    keyRegulator: 'Securities Commission of The Bahamas (SCB)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    region: 'CARIBBEAN',
    legalStatus: 'REGULATED',
    riskScore: 85,
    licensingRequired: true,
    licensingFramework: 'Virtual Asset Service Providers Act 2020. CIMA issues VASP licenses.',
    taxFramework: 'No direct taxation. Fund structures benefit from tax neutrality.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'No CBDC — USD pegged',
    centralBankStance: 'Very progressive — major crypto fund domicile.',
    enforcementHistory: 'Active AML enforcement. Three Arrows Capital liquidation.',
    upcomingLegislation: 'DeFi-specific provisions under consideration',
    stablecoinRules: 'Under VASP Act framework',
    keyRegulator: 'Cayman Islands Monetary Authority (CIMA)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'VG',
    countryName: 'British Virgin Islands',
    region: 'CARIBBEAN',
    legalStatus: 'REGULATED',
    riskScore: 78,
    licensingRequired: true,
    licensingFramework: 'BVI FSC oversees virtual asset business activity.',
    taxFramework: 'No income tax, capital gains tax, or corporate tax.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'No plans — USD territory',
    centralBankStance: 'Supportive — major offshore crypto hub.',
    enforcementHistory: 'Enhanced AML oversight post-FTX era.',
    upcomingLegislation: 'Enhanced VASP disclosure requirements',
    stablecoinRules: 'Under FSC oversight',
    keyRegulator: 'BVI Financial Services Commission',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'HT',
    countryName: 'Haiti',
    region: 'CARIBBEAN',
    legalStatus: 'UNREGULATED',
    riskScore: 20,
    licensingRequired: false,
    licensingFramework: 'No crypto-specific regulation. BRH has not addressed virtual assets.',
    taxFramework: 'No crypto-specific framework.',
    amlStatus: 'NON_COMPLIANT',
    fatfStatus: 'GREY_LIST',
    cbdcStatus: 'No plans',
    centralBankStance: 'No official stance — institutional capacity challenges.',
    enforcementHistory: 'No enforcement capability.',
    upcomingLegislation: 'No known legislative activity',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Banque de la République d\'Haïti (BRH)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    region: 'CARIBBEAN',
    legalStatus: 'DEVELOPING',
    riskScore: 45,
    licensingRequired: false,
    licensingFramework: 'Central Bank studying regulation. No specific crypto framework.',
    taxFramework: 'No specific crypto tax framework.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase',
    centralBankStance: 'Cautious — monitoring regional developments.',
    enforcementHistory: 'Minimal.',
    upcomingLegislation: 'Digital payment regulation updates expected',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Banco Central de la República Dominicana',
    lastUpdated: new Date(),
  },

  // ═══════════════ LATIN AMERICA (11) ═══════════════
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    region: 'LATIN_AMERICA',
    legalStatus: 'REGULATED',
    riskScore: 75,
    licensingRequired: true,
    licensingFramework: 'Legal Framework for Virtual Assets (Law 14,478/2022). BCB designated as regulator.',
    taxFramework: 'Capital gains taxed at 15-22.5%. Monthly reporting for transactions >R$35,000.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'DREX (Real Digital) — pilot phase with 16 banks',
    centralBankStance: 'Progressive — BCB leading CBDC and crypto regulation.',
    enforcementHistory: 'Receita Federal (IRS) active in crypto tax enforcement.',
    upcomingLegislation: 'DREX full launch. Stablecoin-specific regulations.',
    stablecoinRules: 'Under BCB framework — specific guidelines expected 2026',
    keyRegulator: 'Banco Central do Brasil (BCB)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    region: 'LATIN_AMERICA',
    legalStatus: 'DEVELOPING',
    riskScore: 52,
    licensingRequired: false,
    licensingFramework: 'CNV (Securities Commission) regulates token offerings. No comprehensive VASP framework.',
    taxFramework: 'Income tax on crypto profits. Withholding tax on exchanges.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'GREY_LIST',
    cbdcStatus: 'No CBDC plans — focus on currency stabilization',
    centralBankStance: 'Restrictive on purchases (capital controls) but crypto thriving despite restrictions.',
    enforcementHistory: 'BCRA capital controls limit official crypto purchases. P2P markets boom.',
    upcomingLegislation: 'Potential Milei administration deregulation',
    stablecoinRules: 'Not specifically regulated — USDT/USDC widely used as inflation hedge',
    keyRegulator: 'Comisión Nacional de Valores (CNV) + BCRA',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    region: 'LATIN_AMERICA',
    legalStatus: 'DEVELOPING',
    riskScore: 58,
    licensingRequired: false,
    licensingFramework: 'SFC (Superintendencia Financiera) sandbox for crypto. No comprehensive VASP law.',
    taxFramework: 'Crypto profits taxed as capital gains. VAT exemption for crypto.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase with BanRep',
    centralBankStance: 'Cautious — sandbox approach. Banco de la República monitoring.',
    enforcementHistory: 'BitConnect case. SFC warnings about unlicensed platforms.',
    upcomingLegislation: 'Comprehensive crypto regulation bill in Congress',
    stablecoinRules: 'Not specifically regulated',
    keyRegulator: 'Superintendencia Financiera de Colombia (SFC)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    region: 'LATIN_AMERICA',
    legalStatus: 'REGULATED',
    riskScore: 70,
    licensingRequired: true,
    licensingFramework: 'Fintech Law 2018 covers virtual assets. CNBV licenses crypto institutions.',
    taxFramework: 'ISR (income tax) on crypto profits. VAT on crypto services.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Banxico exploring digital peso — no firm timeline',
    centralBankStance: 'Cautious — Banxico has warned about crypto risks.',
    enforcementHistory: 'Bitso as largest regulated exchange. CNBV enforcement active.',
    upcomingLegislation: 'Fintech Law amendments for enhanced crypto oversight',
    stablecoinRules: 'Under Fintech Law framework',
    keyRegulator: 'Comisión Nacional Bancaria y de Valores (CNBV)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'VE',
    countryName: 'Venezuela',
    region: 'LATIN_AMERICA',
    legalStatus: 'PARTIALLY_REGULATED',
    riskScore: 35,
    licensingRequired: true,
    licensingFramework: 'SUNACRIP oversees crypto activities. Petro (PTR) experiment ended.',
    taxFramework: 'Various crypto taxes imposed. Enforcement inconsistent.',
    amlStatus: 'NON_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Petro (failed). Digital bolivar under consideration.',
    centralBankStance: 'Complex — government promoted Petro, now monitoring crypto.',
    enforcementHistory: 'Petro failure. Mining crackdowns and licensing. Sanctions complications.',
    upcomingLegislation: 'New digital asset regulatory framework being drafted',
    stablecoinRules: 'SUNACRIP oversight — USDT widely used for remittances',
    keyRegulator: 'SUNACRIP (Superintendencia Nacional de Criptoactivos)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    region: 'LATIN_AMERICA',
    legalStatus: 'REGULATED',
    riskScore: 72,
    licensingRequired: true,
    licensingFramework: 'Fintech Law 2023 — CMF regulates crypto platforms.',
    taxFramework: 'Capital gains tax on crypto. SII (tax authority) requires reporting.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Research phase with BCCh',
    centralBankStance: 'Progressive — supportive of regulated innovation.',
    enforcementHistory: 'Banks required to serve crypto companies (antitrust ruling).',
    upcomingLegislation: 'CMF implementing Fintech Law secondary regulations',
    stablecoinRules: 'Under Fintech Law framework',
    keyRegulator: 'Comisión para el Mercado Financiero (CMF)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'PE',
    countryName: 'Peru',
    region: 'LATIN_AMERICA',
    legalStatus: 'DEVELOPING',
    riskScore: 48,
    licensingRequired: false,
    licensingFramework: 'No comprehensive crypto legislation. SBS monitoring developments.',
    taxFramework: 'Income tax on crypto gains. No specific crypto tax law.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'BCRP studying digital sol',
    centralBankStance: 'Cautious — BCRP warnings issued.',
    enforcementHistory: 'Minimal enforcement.',
    upcomingLegislation: 'Digital asset regulation bill in Congress',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Superintendencia de Banca, Seguros y AFP (SBS)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'EC',
    countryName: 'Ecuador',
    region: 'LATIN_AMERICA',
    legalStatus: 'DEVELOPING',
    riskScore: 40,
    licensingRequired: false,
    licensingFramework: 'Crypto not banned but not regulated. Dollarized economy complicates approach.',
    taxFramework: 'No specific crypto tax framework.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Dinero Electrónico (discontinued 2018)',
    centralBankStance: 'Cautious — dollarized economy limits monetary policy options.',
    enforcementHistory: 'Minimal.',
    upcomingLegislation: 'Digital assets mentioned in financial modernization bill',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Superintendencia de Bancos del Ecuador',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'PA',
    countryName: 'Panama',
    region: 'LATIN_AMERICA',
    legalStatus: 'DEVELOPING',
    riskScore: 55,
    licensingRequired: false,
    licensingFramework: 'Crypto bill passed legislature but not signed into law. SBP exploring framework.',
    taxFramework: 'Territorial tax system — foreign crypto gains not taxed.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'GREY_LIST',
    cbdcStatus: 'No plans — USD-based economy',
    centralBankStance: 'Mixed signals — legislative momentum but executive hesitancy.',
    enforcementHistory: 'Minimal crypto enforcement.',
    upcomingLegislation: 'Revised crypto regulation bill expected',
    stablecoinRules: 'Not regulated',
    keyRegulator: 'Superintendencia de Bancos de Panamá (SBP)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'UY',
    countryName: 'Uruguay',
    region: 'LATIN_AMERICA',
    legalStatus: 'DEVELOPING',
    riskScore: 60,
    licensingRequired: false,
    licensingFramework: 'BCU proposed regulatory framework for virtual assets in 2024.',
    taxFramework: 'IRPF on crypto gains for residents. Tax reform ongoing.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'e-Peso pilot completed — deployment decision pending',
    centralBankStance: 'Progressive — BCU actively studying regulation.',
    enforcementHistory: 'Minimal.',
    upcomingLegislation: 'BCU virtual asset regulation expected 2026',
    stablecoinRules: 'Under proposed BCU framework',
    keyRegulator: 'Banco Central del Uruguay (BCU)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'SV',
    countryName: 'El Salvador',
    region: 'LATIN_AMERICA',
    legalStatus: 'LEGAL_TENDER',
    riskScore: 90,
    licensingRequired: true,
    licensingFramework: 'Bitcoin Law 2021 — BTC as legal tender. Digital Assets Issuance Act 2023.',
    taxFramework: 'No capital gains tax on Bitcoin. Income tax on crypto business profits.',
    amlStatus: 'PARTIALLY_COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Chivo Wallet (government Bitcoin wallet) — BTC as CBDC substitute',
    centralBankStance: 'Extremely progressive — world first BTC legal tender.',
    enforcementHistory: 'Government is the promoter. IMF concerns about fiscal risk.',
    upcomingLegislation: 'Digital securities regulation. Volcano bonds framework.',
    stablecoinRules: 'Under Digital Assets Issuance Act',
    keyRegulator: 'Comisión Nacional de Activos Digitales',
    lastUpdated: new Date(),
  },

  // ═══════════════ ADDITIONAL KEY MARKETS (7) ═══════════════
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    region: 'MIDDLE_EAST',
    legalStatus: 'REGULATED',
    riskScore: 92,
    licensingRequired: true,
    licensingFramework: 'VARA (Dubai Virtual Assets Regulatory Authority) + ADGM FSRA. Comprehensive VASP framework.',
    taxFramework: 'No personal income tax. 9% corporate tax (from 2023). No crypto-specific tax.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Digital Dirham — mBridge project with BIS',
    centralBankStance: 'Very progressive — Dubai/Abu Dhabi competing for crypto hub status.',
    enforcementHistory: 'Active VARA enforcement. Binance licensed.',
    upcomingLegislation: 'VARA expanding scope to DeFi and NFTs',
    stablecoinRules: 'AED-backed stablecoins under VARA regulation',
    keyRegulator: 'VARA (Dubai) + ADGM FSRA (Abu Dhabi)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    region: 'ASIA_PACIFIC',
    legalStatus: 'REGULATED',
    riskScore: 90,
    licensingRequired: true,
    licensingFramework: 'Payment Services Act 2019 (amended 2024). MAS issues Major Payment Institution licenses for crypto.',
    taxFramework: 'No capital gains tax. GST exemption for digital payment tokens.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Project Orchid — wholesale CBDC. Purpose Bound Money trials.',
    centralBankStance: 'Progressive with guardrails. MAS global fintech leader.',
    enforcementHistory: 'Three Arrows Capital collapse. Terraform Labs. Strict retail restrictions.',
    upcomingLegislation: 'Stablecoin regulatory framework. DPT restrictions.',
    stablecoinRules: 'MAS Stablecoin Regulatory Framework (2023) — single-currency pegged stablecoins',
    keyRegulator: 'Monetary Authority of Singapore (MAS)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    region: 'EUROPE',
    legalStatus: 'REGULATED',
    riskScore: 80,
    licensingRequired: true,
    licensingFramework: 'FCA registration for crypto businesses (MLR 2017). Financial Services and Markets Act 2023 covers crypto.',
    taxFramework: 'Capital gains tax on crypto. HMRC guidance comprehensive.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Digital Pound (Britcoin) — consultation completed, design phase',
    centralBankStance: 'Constructive — BoE and FCA taking phased approach.',
    enforcementHistory: 'FCA banned Binance (later partially reversed). Crypto ad regulations.',
    upcomingLegislation: 'Digital Securities Sandbox. Stablecoin regulation. Crypto promotion rules.',
    stablecoinRules: 'Under Financial Services and Markets Act — fiat-backed stablecoin framework',
    keyRegulator: 'Financial Conduct Authority (FCA)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    region: 'SOUTH_ASIA',
    legalStatus: 'REGULATED',
    riskScore: 55,
    licensingRequired: false,
    licensingFramework: 'No specific licensing. RBI circular (2018 ban) overturned by Supreme Court. Taxation implies legality.',
    taxFramework: '30% tax on crypto gains. 1% TDS on transfers >₹10,000.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Digital Rupee (e₹) — pilot with 5 banks',
    centralBankStance: 'Cautious — RBI prefers ban but government chose taxation route.',
    enforcementHistory: 'ED (Enforcement Directorate) raids on WazirX, Vauld. Tax enforcement.',
    upcomingLegislation: 'Comprehensive crypto regulation bill (repeatedly delayed)',
    stablecoinRules: 'Not specifically regulated — RBI discourages',
    keyRegulator: 'Ministry of Finance + RBI + SEBI',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    region: 'SOUTHEAST_ASIA',
    legalStatus: 'REGULATED',
    riskScore: 65,
    licensingRequired: true,
    licensingFramework: 'OJK (Financial Services Authority) took over from BAPPEBTI in 2025. Crypto exchanges must be licensed.',
    taxFramework: '0.1% income tax + 0.11% VAT on crypto transactions.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Digital Rupiah — Project Garuda in development',
    centralBankStance: 'Progressive regulatory transition from commodity to financial asset classification.',
    enforcementHistory: 'Multiple unlicensed exchange closures. Regulatory transition challenges.',
    upcomingLegislation: 'OJK finalizing comprehensive crypto exchange regulations',
    stablecoinRules: 'Under OJK oversight',
    keyRegulator: 'Otoritas Jasa Keuangan (OJK)',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    region: 'SOUTHEAST_ASIA',
    legalStatus: 'REGULATED',
    riskScore: 68,
    licensingRequired: true,
    licensingFramework: 'BSP Circular 944 — VASP registration. SEC oversight for token offerings.',
    taxFramework: 'Income tax on crypto profits. No specific crypto tax rate.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Project CBDCPh — wholesale CBDC pilot',
    centralBankStance: 'Progressive — BSP has licensed multiple VASPs.',
    enforcementHistory: 'SEC enforcement against unlicensed token offerings.',
    upcomingLegislation: 'Enhanced VASP regulations. Stablecoin framework.',
    stablecoinRules: 'Under BSP oversight',
    keyRegulator: 'Bangko Sentral ng Pilipinas (BSP) + SEC Philippines',
    lastUpdated: new Date(),
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    region: 'SOUTHEAST_ASIA',
    legalStatus: 'REGULATED',
    riskScore: 70,
    licensingRequired: true,
    licensingFramework: 'Digital Asset Decree B.E. 2561 (2018). SEC Thailand licenses exchanges and brokers.',
    taxFramework: '15% capital gains tax on crypto (delayed implementation). VAT exemption for crypto trading.',
    amlStatus: 'COMPLIANT',
    fatfStatus: 'NOT_LISTED',
    cbdcStatus: 'Retail CBDC pilot — mBridge cross-border project with BIS',
    centralBankStance: 'Moderate — SEC regulates, BoT discourages crypto for payments.',
    enforcementHistory: 'Zipmex suspension. Multiple exchange compliance actions.',
    upcomingLegislation: 'Digital asset tax finalization. DeFi regulation framework.',
    stablecoinRules: 'Under SEC oversight — THB-backed stablecoin requirements',
    keyRegulator: 'Securities and Exchange Commission Thailand',
    lastUpdated: new Date(),
  },
];

export default regulatoryCountrySeedData;
