/**
 * FinanceService — facade over category modules (BE-1-2).
 */
import { FinanceInstanceMethods } from './finance/financeInstanceMethods';
import { FinanceDeposits } from './finance/categories/deposits';
import { FinanceWithdrawals } from './finance/categories/withdrawals';
import { FinanceTransfers } from './finance/categories/transfers';
import { FinancePayments } from './finance/categories/payments';
import { FinanceRefunds } from './finance/categories/refunds';
import { FinanceStaking } from './finance/categories/staking';
import { FinanceConversions } from './finance/categories/conversions';
import { FinanceAirdrops } from './finance/categories/airdrops';
import { FinanceEscrow } from './finance/categories/escrow';
import { FinanceGifts } from './finance/categories/gifts';
import { FinanceFeesCommissions } from './finance/categories/feesCommissions';
import { FinanceRevenue } from './finance/categories/revenue';
import { FinanceExpenses } from './finance/categories/expenses';
import { FinanceAuditReporting } from './finance/categories/auditReporting';
import { FinanceSecurity } from './finance/categories/security';
import { FinanceTax } from './finance/categories/tax';
import { FinanceSubscriptions } from './finance/categories/subscriptions';
import { FinanceWalletManagement } from './finance/categories/walletManagement';
import { FinanceGateways } from './finance/categories/gateways';
import { FinanceAdvanced } from './finance/categories/advanced';
import { generateTransactionHash, logFinanceOperation } from './finance/financeHelpers';

export * from './finance/financeTypes';

export class FinanceService extends FinanceInstanceMethods {
  static generateTransactionHash = generateTransactionHash;
  static logFinanceOperation = logFinanceOperation;

  static depositFromExternalWallet = FinanceDeposits.depositFromExternalWallet;
  static depositViaMobileMoney = FinanceDeposits.depositViaMobileMoney;
  static depositViaCard = FinanceDeposits.depositViaCard;
  static depositViaBankTransfer = FinanceDeposits.depositViaBankTransfer;
  static withdrawToExternalWallet = FinanceWithdrawals.withdrawToExternalWallet;
  static withdrawViaMobileMoney = FinanceWithdrawals.withdrawViaMobileMoney;
  static withdrawToBankAccount = FinanceWithdrawals.withdrawToBankAccount;
  static transferUserToUser = FinanceTransfers.transferUserToUser;
  static transferAdminToUser = FinanceTransfers.transferAdminToUser;
  static transferUserToWeWallet = FinanceTransfers.transferUserToWeWallet;
  static transferWeWalletToUser = FinanceTransfers.transferWeWalletToUser;
  static batchTransfer = FinanceTransfers.batchTransfer;
  static processSubscriptionPayment = FinancePayments.processSubscriptionPayment;
  static processProductPayment = FinancePayments.processProductPayment;
  static processServicePayment = FinancePayments.processServicePayment;
  static processPremiumContentPayment = FinancePayments.processPremiumContentPayment;
  static processBoostCampaignPayment = FinancePayments.processBoostCampaignPayment;
  static processFullRefund = FinanceRefunds.processFullRefund;
  static processPartialRefund = FinanceRefunds.processPartialRefund;
  static processSubscriptionRefund = FinanceRefunds.processSubscriptionRefund;
  static handleChargeback = FinanceRefunds.handleChargeback;
  static lockStaking = FinanceStaking.lockStaking;
  static unlockStaking = FinanceStaking.unlockStaking;
  static claimStakingRewards = FinanceStaking.claimStakingRewards;
  static convertCEToJOY = FinanceConversions.convertCEToJOY;
  static convertJOYToFiat = FinanceConversions.convertJOYToFiat;
  static convertJOYToCrypto = FinanceConversions.convertJOYToCrypto;
  static createAirdropCampaign = FinanceAirdrops.createAirdropCampaign;
  static claimAirdrop = FinanceAirdrops.claimAirdrop;
  static distributeAirdrop = FinanceAirdrops.distributeAirdrop;
  static createEscrow = FinanceEscrow.createEscrow;
  static releaseEscrow = FinanceEscrow.releaseEscrow;
  static handleEscrowDispute = FinanceEscrow.handleEscrowDispute;
  static sendGift = FinanceGifts.sendGift;
  static sendTip = FinanceGifts.sendTip;
  static sendDonation = FinanceGifts.sendDonation;
  static commissionReferral = FinanceFeesCommissions.commissionReferral;
  static commissionAffiliate = FinanceFeesCommissions.commissionAffiliate;
  static trackTransactionFeesRevenue = FinanceRevenue.trackTransactionFeesRevenue;
  static trackServicesRevenue = FinanceRevenue.trackServicesRevenue;
  static trackPartnershipsRevenue = FinanceRevenue.trackPartnershipsRevenue;
  static expenseCreatorPayment = FinanceExpenses.expenseCreatorPayment;
  static expenseReferralPayout = FinanceExpenses.expenseReferralPayout;
  static expenseOperational = FinanceExpenses.expenseOperational;
  static expenseMarketing = FinanceExpenses.expenseMarketing;
  static expenseDevelopment = FinanceExpenses.expenseDevelopment;
  static expenseSupport = FinanceExpenses.expenseSupport;
  static expenseCompliance = FinanceExpenses.expenseCompliance;
  static auditWallet = FinanceAuditReporting.auditWallet;
  static auditUserFinancial = FinanceAuditReporting.auditUserFinancial;
  static reportTransaction = FinanceAuditReporting.reportTransaction;
  static reportRevenue = FinanceAuditReporting.reportRevenue;
  static reportPayouts = FinanceAuditReporting.reportPayouts;
  static reportReconciliation = FinanceAuditReporting.reportReconciliation;
  static securityOTPVerify = FinanceSecurity.securityOTPVerify;
  static security2FA = FinanceSecurity.security2FA;
  static securityWalletFreeze = FinanceSecurity.securityWalletFreeze;
  static securityWhitelistAdd = FinanceSecurity.securityWhitelistAdd;
  static securityWhitelistRemove = FinanceSecurity.securityWhitelistRemove;
  static securityFraudDetection = FinanceSecurity.securityFraudDetection;
  static securityTransactionLimit = FinanceSecurity.securityTransactionLimit;
  static taxCalculation = FinanceTax.taxCalculation;
  static taxReportGenerate = FinanceTax.taxReportGenerate;
  static complianceKYC = FinanceTax.complianceKYC;
  static complianceAML = FinanceTax.complianceAML;
  static subscriptionAutoRenew = FinanceSubscriptions.subscriptionAutoRenew;
  static subscriptionUpgrade = FinanceSubscriptions.subscriptionUpgrade;
  static subscriptionDowngrade = FinanceSubscriptions.subscriptionDowngrade;
  static subscriptionPause = FinanceSubscriptions.subscriptionPause;
  static subscriptionCancel = FinanceSubscriptions.subscriptionCancel;
  static walletCreate = FinanceWalletManagement.walletCreate;
  static walletViewBalance = FinanceWalletManagement.walletViewBalance;
  static walletViewHistory = FinanceWalletManagement.walletViewHistory;
  static walletSetLimits = FinanceWalletManagement.walletSetLimits;
  static walletRecovery = FinanceWalletManagement.walletRecovery;
  static gatewayStripe = FinanceGateways.gatewayStripe;
  static gatewayPayPal = FinanceGateways.gatewayPayPal;
  static gatewayMobileMoney = FinanceGateways.gatewayMobileMoney;
  static gatewayCrypto = FinanceGateways.gatewayCrypto;
  static gatewayBankTransfer = FinanceGateways.gatewayBankTransfer;
  static bulkTransferAdvanced = FinanceAdvanced.bulkTransferAdvanced;
  static scheduledPayment = FinanceAdvanced.scheduledPayment;
  static recurringPayment = FinanceAdvanced.recurringPayment;
  static paymentLink = FinanceAdvanced.paymentLink;
  static invoiceGeneration = FinanceAdvanced.invoiceGeneration;
}

export const financeService = new FinanceService();
